// monitor-web/src/App.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n';
import { setLocale, type Locale } from './i18n';
import StatusView from './views/StatusView.vue';

const { t, locale } = useI18n();

function toggleLocale() {
  setLocale((locale.value === 'en' ? 'zh-CN' : 'en') as Locale);
}

function toggleTheme() {
  const dark = document.documentElement.classList.toggle('dark');
  localStorage.setItem('infinia.monitor.theme', dark ? 'dark' : 'light');
}
</script>

<template>
  <div class="min-h-full">
    <!-- Minimal chrome: this app is one page, the status page. -->
    <header class="header-bar">
      <div class="mx-auto flex max-w-5xl items-center justify-between px-4 py-3">
        <div class="flex items-center gap-2.5">
          <img src="/infinia-logo.svg" alt="" class="h-6 w-6" />
          <div class="leading-tight">
            <div class="text-sm font-bold">{{ t('app.title') }}</div>
            <div class="text-[11px] text-slate-400">{{ t('app.statusTitle') }}</div>
          </div>
        </div>
        <div class="flex items-center gap-1">
          <button type="button" class="btn btn-ghost btn-sm" :aria-label="t('app.themeToggle')" @click="toggleTheme">
            <span aria-hidden="true">◐</span>
          </button>
          <button type="button" class="btn btn-ghost btn-sm" @click="toggleLocale">
            {{ locale === 'en' ? '中' : 'EN' }}
          </button>
        </div>
      </div>
    </header>
    <main class="mx-auto max-w-5xl px-4 py-8">
      <StatusView />
    </main>
  </div>
</template>

// monitor-web/src/App.tsx
import { useState } from 'react';
import { motion } from 'motion/react';
import { useTranslation } from 'react-i18next';
import { setLocale } from './i18n';
import StatusView from './views/StatusView';
export default function App() {
  const { t, i18n } = useTranslation();
  const [dark, setDark] = useState(document.documentElement.classList.contains('dark'));
  return <>
    <header className="header-bar"><div className="shell nav">
      <a className="identity" href="/"><img src="/infinia-logo.svg" alt="" /><strong>Infinia</strong><span>{t('app.statusTitle')}</span></a>
      <div className="actions">
        <button className="btn btn-ghost" onClick={() => setLocale(i18n.language === 'en' ? 'zh-CN' : 'en')}>{i18n.language === 'en' ? '中文' : 'EN'}</button>
        <button className="btn btn-ghost" aria-label={t('app.themeToggle')} onClick={() => {
          document.documentElement.classList.toggle('dark', !dark);
          window.localStorage.setItem('infinia.monitor.theme', dark ? 'light' : 'dark'); setDark(!dark);
        }}><motion.span key={String(dark)} initial={{ opacity: 0, rotate: -45 }} animate={{ opacity: 1, rotate: 0 }} aria-hidden="true">{dark ? '☀' : '☾'}</motion.span></button>
      </div>
    </div></header>
    <main className="shell"><StatusView /></main>
  </>;
}
