// store-web/src/views/CallbackView.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { completeLogin, useAuthStore } from '../stores/auth';
import { ProgressBar } from '@infinia/magic-ui-vue';

const { t } = useI18n();
const route = useRoute();
const router = useRouter();
const auth = useAuthStore();
const failed = ref(false);

onMounted(async () => {
  const code = route.query.code as string | undefined;
  const state = route.query.state as string | undefined;
  if (code && state) {
    const ok = await completeLogin(code, state);
    if (ok) {
      await auth.load();
      const redirect = sessionStorage.getItem('infinia.store.redirect') ?? '/';
      sessionStorage.removeItem('infinia.store.redirect');
      router.replace(redirect);
      return;
    }
  }
  failed.value = true;
});
</script>

<template>
  <div class="mx-auto max-w-md space-y-4 py-20 text-center">
    <template v-if="!failed">
      <p>{{ t('auth.callbackWorking') }}</p>
      <ProgressBar />
    </template>
    <p v-else class="text-red-600 dark:text-red-400">{{ t('auth.callbackFailed') }}</p>
  </div>
</template>

// store-web/src/views/CallbackView.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router';
import { useTranslation } from 'react-i18next';
import { completeLogin, useAuth } from '../stores/auth';
import ProgressBar from '../components/ProgressBar';

export default function CallbackView() {
  const { t } = useTranslation();
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const auth = useAuth();
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    const code = searchParams.get('code') ?? undefined;
    const state = searchParams.get('state') ?? undefined;
    void (async () => {
      if (code && state) {
        const ok = await completeLogin(code, state);
        if (ok) {
          await auth.load();
          const redirect =
            sessionStorage.getItem('infinia.store.redirect') ?? '/store';
          sessionStorage.removeItem('infinia.store.redirect');
          navigate(redirect, { replace: true });
          return;
        }
      }
      setFailed(true);
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="mx-auto max-w-md space-y-4 py-20 text-center">
      {!failed ? (
        <>
          <p>{t('auth.callbackWorking')}</p>
          <ProgressBar />
        </>
      ) : (
        <>
          <p className="font-medium text-danger" role="alert">
            {t('auth.callbackFailed')}
          </p>
          <div className="flex justify-center gap-2">
            <button
              type="button"
              className="btn btn-primary"
              onClick={() => navigate('/store/signin')}
            >
              {t('nav.signIn')}
            </button>
            <button
              type="button"
              className="btn btn-secondary"
              onClick={() => navigate('/store')}
            >
              {t('common.backHome')}
            </button>
          </div>
        </>
      )}
    </div>
  );
}
