// store-web/src/components/LoadingGrid.tsx
export default function LoadingGrid({ count = 6 }: { count?: number }) {
  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3" aria-busy="true">
      {Array.from({ length: count }, (_, i) => (
        <div key={i} className="h-44 animate-pulse rounded-lg bg-surface" />
      ))}
    </div>
  );
}

// store-web/src/components/LoadingGrid.vue
<script setup lang="ts">
defineProps<{ count?: number }>();
const defaultCount = 6;
</script>

<template>
  <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3" aria-busy="true">
    <div
      v-for="i in count ?? defaultCount"
      :key="i"
      class="h-44 animate-pulse rounded-lg bg-surface dark:bg-slate-900"
    />
  </div>
</template>
