// store-web/src/components/RouteContent.tsx
import { Component, Suspense, type ReactNode } from 'react';
import { useTranslation } from 'react-i18next';
import { useLocation } from 'react-router';
import ErrorState from './ErrorState';

/**
 * Route shell: renders the active view behind a lazy-chunk Suspense fallback
 * and an error boundary that offers a full reload (a reload also replaces an
 * outdated entry bundle after a deployment — matching the old router.onError +
 * onErrorCaptured behaviour). Keyed by pathname so a successful navigation
 * clears a previous failure instead of wedging the router.
 */

function RouteFallback() {
  const { t } = useTranslation();
  return (
    <p role="status" className="py-8 text-center text-muted">
      {t('common.loading')}
    </p>
  );
}

function RouteFailure() {
  const { t } = useTranslation();
  const location = useLocation();
  // A full reload also replaces an outdated entry bundle after a deployment.
  const retry = () =>
    window.location.assign(location.pathname + location.search + location.hash);
  return <ErrorState message={t('common.pageLoadError')} onRetry={retry} />;
}

class RouteErrorBoundary extends Component<
  { children: ReactNode },
  { failed: boolean }
> {
  state = { failed: false };

  static getDerivedStateFromError() {
    return { failed: true };
  }

  render() {
    if (this.state.failed) {
      return <RouteFailure />;
    }
    return this.props.children;
  }
}

export default function RouteContent({ children }: { children: ReactNode }) {
  const location = useLocation();
  return (
    <RouteErrorBoundary key={location.pathname}>
      <Suspense fallback={<RouteFallback />}>{children}</Suspense>
    </RouteErrorBoundary>
  );
}

// store-web/src/components/RouteContent.vue
<script setup lang="ts">
import { onBeforeUnmount, onErrorCaptured, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import ErrorState from './ErrorState.vue';

const router = useRouter();
const route = useRoute();
const { t } = useI18n();
const failed = ref(false);
const loading = ref(route.matched.length === 0);
let retryPath = window.location.pathname + window.location.search + window.location.hash;
const removeBefore = router.beforeEach(() => { loading.value = true; });
const removeAfter = router.afterEach((_to, _from, failure) => {
  loading.value = false;
  if (!failure) failed.value = false;
});
const removeError = router.onError((_error, to) => {
  retryPath = to.fullPath;
  loading.value = false;
  failed.value = true;
});
onErrorCaptured(() => {
  retryPath = route.fullPath;
  loading.value = false;
  failed.value = true;
  return false;
});
onBeforeUnmount(() => { removeBefore(); removeAfter(); removeError(); });

// A full reload also replaces an outdated entry bundle after a deployment.
function retry() { window.location.assign(retryPath); }
</script>

<template>
  <ErrorState v-if="failed" :message="t('common.pageLoadError')" @retry="retry" />
  <template v-else>
    <p v-if="loading" role="status" class="py-8 text-center text-muted">{{ t('common.loading') }}</p>
    <RouterView :key="route.fullPath" />
  </template>
</template>
